ezpublish:
    system:
        default:
            location_view:
                full:
                    agenda_folder:
                        template: OpenWidePublishAgendaBundle:LocationView/full:agenda_folder.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_folder.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda_folder   

                    agenda:
                        template: OpenWidePublishAgendaBundle:LocationView/full:agenda.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda

                    agenda_event:
                        template: OpenWidePublishAgendaBundle:LocationView/full:agenda_event.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_event.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda_event

                line:
                    agenda_event:
                        template: OpenWidePublishAgendaBundle:LocationView/line:agenda_event.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_event.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda_event
                    agenda_schedule:
                        template: OpenWidePublishAgendaBundle:LocationView/line:agenda_schedule.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_schedule.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda_schedule  

                bloc:
                    agenda_folder:
                        template: OpenWidePublishAgendaBundle:LocationView/bloc:agenda_folder.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_folder.view:viewLocation"
                        match:
                            Identifier\ContentType: agenda_folder                                

            content_view:
                embed_agenda:
                    agenda_schedule:
                        template: OpenWidePublishAgendaBundle:ContentView/embed_agenda:agenda_schedule.html.twig
                        controller: "open_wide_publish_agenda.controller.agenda_schedule.view:viewContent"
                        match:
                            Identifier\ContentType: agenda_schedule

            image_variations:
                agenda_event_embed:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [220] }
                        - { name: geometry/crop, params: [220, 165, 0, 0] }
