ezpublish:
    system:
        default:
            location_view:
                full:
                    event_folder:
                        template: OpenWidePublishAgendaBundle:full:event_folder.html.twig
                        controller: "open_wide_publish_agenda.controller.event_folder.view:viewLocation"
                        match:
                            Identifier\ContentType: event_folder   

                    event_liste:
                        template: OpenWidePublishAgendaBundle::event_liste.html.twig
                        controller: "open_wide_publish_agenda.controller.event_liste.view:viewLocation"
                        match:
                            Identifier\ContentType: event_liste

                    event_agenda:
                        template: OpenWidePublishAgendaBundle:full:event_agenda.html.twig
                        controller: "open_wide_publish_agenda.controller.event_agenda.view:viewLocation"
                        match:
                            Identifier\ContentType: event_agenda

                line:
                    event_agenda:
                        template: OpenWidePublishAgendaBundle:line:event_agenda.html.twig
                        controller: "open_wide_publish_agenda.controller.event_agenda.view:viewLocation"
                        match:
                            Identifier\ContentType: event_agenda
                    event_date:
                        template: OpenWidePublishAgendaBundle:line:event_date.html.twig
                        controller: "open_wide_publish_agenda.controller.event_date.view:viewLocation"
                        match:
                            Identifier\ContentType: event_date  

                bloc:
                    event_folder:
                        template: OpenWidePublishAgendaBundle:bloc:event_folder.html.twig
                        controller: "open_wide_publish_agenda.controller.event_folder.view:viewLocation"
                        match:
                            Identifier\ContentType: event_folder                                

            content_view:
                embed_agenda:
                    event_date:
                        template: OpenWidePublishAgendaBundle:content_view/embed:event_date.html.twig
                        controller: "open_wide_publish_agenda.controller.event_date.view:viewContent"
                        match:
                            Identifier\ContentType: event_date

            image_variations:
                event_agenda_embed:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [220] }
                        - { name: geometry/crop, params: [220, 165, 0, 0] }
