open_wide_publish_agenda_event_list_json:
    path:     /agenda/list/events.json
    defaults: { _controller: open_wide_publish_agenda.controller.json:eventsListJSONAction, _format: json }
    requirements: { _format: (xml|json), _method: GET }
