parameters:
    open_wide_publish_agenda.configuration_mapper.class: 'OpenWide\Publish\AgendaBundle\LegacyMapper\Configuration'
    open_wide_publish_agenda.content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\ContentRepository'
    open_wide_publish_agenda.agenda_folder_content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\AgendaFolderContentRepositiry'
    open_wide_publish_agenda.agenda_content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\AgendaFolderContentRepositiry'
    open_wide_publish_agenda.agenda_event_content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\AgendaEventContentRepositiry'
    open_wide_publish_agenda.agenda_schedule_content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\AgendaScheduleContentRepositiry'

services:

    open_wide_publish_agenda.configuration_mapper:
        class: %open_wide_publish_agenda.configuration_mapper.class%
        arguments:
            - @ezpublish.config.resolver
        tags:
            - { name: kernel.event_subscriber }
            
    open_wide_publish_agenda.content_repository:
        class: %open_wide_publish_agenda.content_repository.class%
        arguments: [@service_container]
        calls:
            - [ setContainer,[ @service_container ] ]
            
    open_wide_publish_agenda.agenda_folder_content_repository:
        class: %open_wide_publish_agenda.agenda_folder_content_repository.class%
        parent: open_wide_publish_agenda.content_repository
            
    open_wide_publish_agenda.agenda_content_repository:
        class: %open_wide_publish_agenda.agenda_content_repository.class%
        parent: open_wide_publish_agenda.content_repository
            
    open_wide_publish_agenda.agenda_event_content_repository:
        class: %open_wide_publish_agenda.agenda_event_content_repository.class%
        parent: open_wide_publish_agenda.content_repository
            
    open_wide_publish_agenda.agenda_schedule_content_repository:
        class: %open_wide_publish_agenda.agenda_schedule_content_repository.class%
        parent: open_wide_publish_agenda.content_repository
