parameters:
    open_wide_publish_agenda.content_repository.class: 'OpenWide\Publish\AgendaBundle\Service\ContentRepository'
    open_wide_publish_agenda.configuration_mapper.class: 'OpenWide\Publish\AgendaBundle\LegacyMapper\Configuration'

services:
    open_wide_publish_agenda.content_repository:
        class: %open_wide_publish_agenda.content_repository.class%
        arguments: [@service_container]
        calls:
            - [ setContainer,[ @service_container ] ]

    open_wide_publish_agenda.configuration_mapper:
        class: %open_wide_publish_agenda.configuration_mapper.class%
        arguments:
            - @ezpublish.config.resolver
        tags:
            - { name: kernel.event_subscriber }
